// react-app/src/components/trading/Watchlist.tsx
import { useState } from 'react'
import { cn, formatPrice, formatChange, formatPercent, formatVolume } from '@/lib/utils'
import { WATCHLIST_DATA, type WatchlistItem } from '@/lib/mock-data'
import { ArrowUpDown } from 'lucide-react'

type SortKey = keyof WatchlistItem
type SortDir = 'asc' | 'desc'

export function Watchlist() {
  const [sortKey, setSortKey] = useState<SortKey>('symbol')
  const [sortDir, setSortDir] = useState<SortDir>('asc')
  const [selectedSymbol, setSelectedSymbol] = useState<string | null>('AAPL')

  const handleSort = (key: SortKey) => {
    if (sortKey === key) {
      setSortDir(prev => prev === 'asc' ? 'desc' : 'asc')
    } else {
      setSortKey(key)
      setSortDir('asc')
    }
  }

  const sorted = [...WATCHLIST_DATA].sort((a, b) => {
    const aVal = a[sortKey]
    const bVal = b[sortKey]
    const mult = sortDir === 'asc' ? 1 : -1
    if (typeof aVal === 'string') return mult * aVal.localeCompare(bVal as string)
    return mult * ((aVal as number) - (bVal as number))
  })

  const SortHeader = ({ label, field }: { label: string; field: SortKey }) => (
    <th
      className="px-3 py-1.5 text-left text-[11px] font-medium text-muted-foreground cursor-pointer hover:text-foreground select-none"
      onClick={() => handleSort(field)}
    >
      <span className="flex items-center gap-1">
        {label}
        {sortKey === field && (
          <ArrowUpDown className="w-3 h-3" />
        )}
      </span>
    </th>
  )

  return (
    <div className="bg-card h-full flex flex-col overflow-hidden">
      <div className="flex items-center justify-between px-3 py-2 border-b border-border shrink-0">
        <span className="text-xs font-medium">First list</span>
      </div>
      <div className="overflow-auto flex-1">
        <table className="w-full text-xs">
          <thead className="bg-elevated sticky top-0">
            <tr>
              <th className="w-8 px-2 py-1.5 text-left text-[11px] font-medium text-muted-foreground">#</th>
              <SortHeader label="Symbol" field="symbol" />
              <SortHeader label="Net chg" field="change" />
              <SortHeader label="Chg %" field="changePct" />
              <SortHeader label="Last" field="last" />
              <SortHeader label="Volume" field="volume" />
            </tr>
          </thead>
          <tbody>
            {sorted.map((item, i) => {
              const isPositive = item.change > 0
              const isNeutral = item.change === 0
              const colorClass = isNeutral ? 'text-muted-foreground' : isPositive ? 'text-buy' : 'text-sell'

              return (
                <tr
                  key={item.symbol}
                  onClick={() => setSelectedSymbol(item.symbol)}
                  className={cn(
                    'cursor-pointer transition-colors border-b border-border/50',
                    selectedSymbol === item.symbol
                      ? 'bg-sell-muted'
                      : 'hover:bg-elevated'
                  )}
                >
                  <td className="px-2 py-1.5 text-muted-foreground">{i + 1}</td>
                  <td className="px-3 py-1.5 font-medium">{item.symbol}</td>
                  <td className={cn('px-3 py-1.5 font-mono', colorClass)}>
                    {isPositive ? '▲' : isNeutral ? '▲' : '▼'} ${formatChange(Math.abs(item.change))}
                  </td>
                  <td className={cn('px-3 py-1.5 font-mono', colorClass)}>
                    {isPositive ? '▲' : isNeutral ? '▲' : '▼'} {formatPercent(Math.abs(item.changePct))}
                  </td>
                  <td className="px-3 py-1.5 font-mono text-right">${formatPrice(item.last)}</td>
                  <td className="px-3 py-1.5 font-mono text-right text-muted-foreground">{formatVolume(item.volume)}</td>
                </tr>
              )
            })}
          </tbody>
        </table>
      </div>
    </div>
  )
}

// angular-app/src/app/trading/watchlist.component.ts
import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { TableModule } from 'primeng/table';
import { WATCHLIST_DATA, formatPrice, formatVolume, type WatchlistItem } from '../shared/mock-data';

@Component({
  selector: 'app-watchlist',
  standalone: true,
  imports: [CommonModule, TableModule],
  template: `
    <div class="ds-panel">
      <div class="ds-panel-header">
        <span class="ds-panel-title">First list</span>
      </div>
      <p-table
        [value]="data"
        [scrollable]="true"
        scrollHeight="flex"
        selectionMode="single"
        [(selection)]="selectedItem"
        dataKey="symbol"
        [rowHover]="true"
        styleClass="p-datatable-sm"
      >
        <ng-template #header>
          <tr>
            <th style="width: 2rem">#</th>
            <th pSortableColumn="symbol">Symbol <p-sortIcon field="symbol" /></th>
            <th pSortableColumn="change">Net chg <p-sortIcon field="change" /></th>
            <th pSortableColumn="changePct">Chg % <p-sortIcon field="changePct" /></th>
            <th pSortableColumn="last" style="text-align: right">Last <p-sortIcon field="last" /></th>
            <th pSortableColumn="volume" style="text-align: right">Volume <p-sortIcon field="volume" /></th>
          </tr>
        </ng-template>
        <ng-template #body let-item let-rowIndex="rowIndex">
          <tr [pSelectableRow]="item">
            <td class="ds-muted">{{ rowIndex + 1 }}</td>
            <td class="ds-bold">{{ item.symbol }}</td>
            <td [class]="getColorClass(item.change) + ' ds-mono'">
              {{ getArrow(item.change) }} {{ '$' + formatAbsChange(item.change) }}
            </td>
            <td [class]="getColorClass(item.changePct) + ' ds-mono'">
              {{ getArrow(item.changePct) }} {{ formatAbsPercent(item.changePct) }}
            </td>
            <td class="ds-mono" style="text-align: right">{{ '$' + formatPrice(item.last) }}</td>
            <td class="ds-mono ds-muted" style="text-align: right">{{ formatVolume(item.volume) }}</td>
          </tr>
        </ng-template>
      </p-table>
    </div>
  `,
  styles: [`
    :host { display: block; height: 100%; width: 100%; }
    .ds-panel {
      background: var(--ds-card);
      overflow: hidden;
      height: 100%;
      display: flex;
      flex-direction: column;
    }
    .ds-panel-header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding: 0.5rem 0.75rem;
      border-bottom: 1px solid var(--ds-border);
    }
    .ds-panel-title { font-size: 0.75rem; font-weight: 500; }
    .ds-mono { font-family: var(--ds-font-mono) !important; }
    .ds-bold { font-weight: 500; }
    .ds-muted { color: var(--ds-muted-foreground) !important; }
    .ds-buy-text { color: var(--ds-buy) !important; }
    .ds-sell-text { color: var(--ds-sell) !important; }
  `],
})
export class WatchlistComponent {
  data = WATCHLIST_DATA;
  selectedItem = signal<WatchlistItem | null>(WATCHLIST_DATA[0]);
  formatPrice = formatPrice;
  formatVolume = formatVolume;

  getColorClass(value: number): string {
    if (value > 0) return 'ds-buy-text';
    if (value < 0) return 'ds-sell-text';
    return 'ds-muted';
  }

  getArrow(value: number): string {
    return value < 0 ? '▼' : '▲';
  }

  formatAbsChange(value: number): string {
    return Math.abs(value).toFixed(2);
  }

  formatAbsPercent(value: number): string {
    return Math.abs(value).toFixed(2) + '%';
  }
}
