// react-app/src/components/trading/fi/DashboardPanel.tsx
import { cn } from '@/lib/utils'
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, ReferenceLine } from 'recharts'
import type { Treasury, CorpBond, YieldCurvePoint, CDXIndex } from './marketData'
import { fmtYield, fmtBps, fmtPnL, fmtDV01, BASE_ORDERS, BASE_POSITIONS } from './marketData'

interface Props {
  treasuries: Treasury[]
  corpBonds: CorpBond[]
  yieldCurve: YieldCurvePoint[]
  cdxIndices: CDXIndex[]
}

const TOTAL_PNL_TODAY = 93_170
const TOTAL_PNL_MTD   = 243_135
const TOTAL_PNL_YTD   = 590_320
const TOTAL_DV01       = 420_945
const TOTAL_CS01       = 57_182

function KpiCard({ label, value, sub, valueClass }: { label: string; value: string; sub?: string; valueClass?: string }) {
  return (
    <div className="bg-card border border-border rounded-xl px-4 py-3 flex flex-col gap-0.5">
      <span className="text-[10px] text-muted-foreground uppercase tracking-widest">{label}</span>
      <span className={cn('text-xl font-semibold font-mono leading-tight mt-0.5', valueClass)}>{value}</span>
      {sub && <span className="text-[10px] text-muted-foreground mt-0.5">{sub}</span>}
    </div>
  )
}

function StatusBadge({ status }: { status: string }) {
  const cls: Record<string, string> = {
    Filled:    'bg-buy/15 text-buy',
    Working:   'bg-primary/15 text-primary',
    Partial:   'bg-warning/15 text-warning',
    Cancelled: 'bg-muted text-muted-foreground',
  }
  return <span className={cn('text-[10px] px-1.5 py-0.5 rounded-full font-medium', cls[status] ?? 'bg-muted text-muted-foreground')}>{status}</span>
}

export function DashboardPanel({ treasuries, yieldCurve, cdxIndices }: Props) {
  const tsy2Y  = treasuries.find(t => t.tenor === '2Y')
  const tsy10Y = treasuries.find(t => t.tenor === '10Y')
  const tsy30Y = treasuries.find(t => t.tenor === '30Y')
  const cdxIG  = cdxIndices.find(c => c.name.includes('NA.IG') && c.tenor === '5Y')
  const cdxHY  = cdxIndices.find(c => c.name.includes('NA.HY'))

  const recentOrders = BASE_ORDERS.slice(-6).reverse()
  const benchmarks = [
    { label: '2Y  UST', yield: tsy2Y?.bidYield,  change: tsy2Y?.change },
    { label: '10Y UST', yield: tsy10Y?.bidYield, change: tsy10Y?.change },
    { label: '30Y UST', yield: tsy30Y?.bidYield, change: tsy30Y?.change },
    { label: 'CDX IG',  yield: cdxIG ? (cdxIG.bidSpread + cdxIG.askSpread) / 2 : undefined,  change: cdxIG?.change, isBps: true },
    { label: 'CDX HY',  yield: cdxHY ? (cdxHY.bidSpread + cdxHY.askSpread) / 2 : undefined, change: cdxHY?.change, isBps: true },
  ]

  const yMin = Math.floor(Math.min(...yieldCurve.map(d => d.yield)) * 10) / 10 - 0.1
  const yMax = Math.ceil (Math.max(...yieldCurve.map(d => d.yield)) * 10) / 10 + 0.1

  return (
    <div className="h-full flex flex-col gap-3 p-3 overflow-hidden">

      {/* KPI row */}
      <div className="grid grid-cols-5 gap-2 shrink-0">
        <KpiCard label="P&L Today"   value={fmtPnL(TOTAL_PNL_TODAY)} valueClass={TOTAL_PNL_TODAY >= 0 ? 'text-buy' : 'text-sell'} sub="All strategies" />
        <KpiCard label="P&L MTD"     value={fmtPnL(TOTAL_PNL_MTD)}   valueClass={TOTAL_PNL_MTD >= 0 ? 'text-buy' : 'text-sell'}  sub="March 2026" />
        <KpiCard label="P&L YTD"     value={fmtPnL(TOTAL_PNL_YTD)}   valueClass={TOTAL_PNL_YTD >= 0 ? 'text-buy' : 'text-sell'}  sub="Since Jan 1" />
        <KpiCard label="Net DV01"    value={fmtDV01(TOTAL_DV01)}      sub="Portfolio rate sensitivity" />
        <KpiCard label="Net CS01"    value={fmtDV01(TOTAL_CS01)}      sub="Portfolio credit sensitivity" />
      </div>

      {/* Yield curve + benchmarks — expands to fill remaining height */}
      <div className="flex-1 min-h-0 grid grid-cols-3 gap-3">

        {/* Yield curve — chart fills the card height */}
        <div className="col-span-2 bg-card border border-border rounded-xl flex flex-col overflow-hidden">
          <div className="flex items-center justify-between px-4 py-2.5 border-b border-border shrink-0">
            <div>
              <span className="text-xs font-semibold">US Treasury Yield Curve</span>
              <span className="ml-2 text-[10px] text-muted-foreground">On-The-Run  ·  Live</span>
            </div>
            <div className="flex items-center gap-3 text-[10px] text-muted-foreground">
              <span className="flex items-center gap-1"><span className="w-3 h-0.5 bg-primary rounded inline-block" /> Today</span>
              <span className="flex items-center gap-1"><span className="w-3 h-0.5 bg-muted-foreground rounded inline-block opacity-50" /> Prev Close</span>
            </div>
          </div>
          <div className="flex-1 p-2 min-h-0">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={yieldCurve} margin={{ top: 8, right: 16, left: -8, bottom: 0 }}>
                <defs>
                  <linearGradient id="yieldGrad" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%"  stopColor="var(--color-primary)" stopOpacity={0.15} />
                    <stop offset="95%" stopColor="var(--color-primary)" stopOpacity={0} />
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" stroke="var(--color-border)" strokeOpacity={0.4} />
                <XAxis dataKey="tenor" tick={{ fontSize: 10, fill: 'var(--color-muted-foreground)' }} axisLine={false} tickLine={false} />
                <YAxis domain={[yMin, yMax]} tick={{ fontSize: 10, fill: 'var(--color-muted-foreground)' }} axisLine={false} tickLine={false} tickFormatter={v => v.toFixed(1) + '%'} />
                <Tooltip
                  contentStyle={{ background: 'var(--color-card)', border: '1px solid var(--color-border)', borderRadius: 6, fontSize: 11 }}
                  formatter={(v: any) => [v.toFixed(3) + '%', 'Yield']}
                  labelStyle={{ color: 'var(--color-muted-foreground)', marginBottom: 2 }}
                />
                <Area type="monotone" dataKey="prevYield" stroke="var(--color-muted-foreground)" strokeWidth={1} strokeDasharray="3 3" fill="none" dot={false} />
                <Area type="monotone" dataKey="yield" stroke="var(--color-primary)" strokeWidth={2} fill="url(#yieldGrad)" dot={{ r: 2.5, fill: 'var(--color-primary)', strokeWidth: 0 }} activeDot={{ r: 4 }} />
                <ReferenceLine y={0} stroke="var(--color-border)" />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Benchmarks */}
        <div className="bg-card border border-border rounded-xl overflow-hidden flex flex-col">
          <div className="px-4 py-2.5 border-b border-border shrink-0">
            <span className="text-xs font-semibold">Key Benchmarks</span>
          </div>
          <div className="divide-y divide-border flex-1">
            {benchmarks.map(b => (
              <div key={b.label} className="flex items-center justify-between px-4 py-2.5">
                <span className="text-xs text-muted-foreground font-mono">{b.label}</span>
                <div className="text-right">
                  <div className="text-sm font-mono font-semibold">
                    {b.yield !== undefined ? (b.isBps ? b.yield.toFixed(1) + ' bps' : fmtYield(b.yield)) : '—'}
                  </div>
                  {b.change !== undefined && (
                    <div className={cn('text-[10px] font-mono', b.change < 0 ? 'text-buy' : 'text-sell')}>
                      {fmtBps(b.change)}
                    </div>
                  )}
                </div>
              </div>
            ))}
            <div className="flex items-center justify-between px-4 py-2.5">
              <span className="text-xs text-muted-foreground font-mono">2s10s Slope</span>
              <div className="text-right">
                {tsy2Y && tsy10Y && (() => {
                  const slope = Math.round((tsy10Y.bidYield - tsy2Y.bidYield) * 100)
                  return (
                    <div className={cn('text-sm font-mono font-semibold', slope < 0 ? 'text-sell' : 'text-buy')}>
                      {slope > 0 ? '+' : ''}{slope} bps
                    </div>
                  )
                })()}
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Bottom: Position summary + Recent orders — fixed height, scrollable inside */}
      <div className="grid grid-cols-3 gap-3 shrink-0 h-[210px]">

        {/* Position summary */}
        <div className="bg-card border border-border rounded-xl flex flex-col overflow-hidden">
          <div className="px-4 py-2.5 border-b border-border shrink-0">
            <span className="text-xs font-semibold">Position Summary</span>
          </div>
          <div className="flex-1 overflow-y-auto divide-y divide-border">
            {BASE_POSITIONS.map(p => (
              <div key={p.id} className="flex items-center justify-between px-4 py-1.5 text-[11px]">
                <div>
                  <div className={cn('font-medium', p.direction === 'Long' ? 'text-buy' : 'text-sell')}>
                    {p.direction === 'Long' ? '▲' : '▼'} {p.security}
                  </div>
                  <div className="text-muted-foreground">{p.assetClass}</div>
                </div>
                <div className="text-right font-mono">
                  <div className={cn(p.pnlToday >= 0 ? 'text-buy' : 'text-sell')}>{fmtPnL(p.pnlToday)}</div>
                  <div className="text-muted-foreground text-[10px]">{fmtDV01(Math.abs(p.dv01))} dv01</div>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Recent orders */}
        <div className="col-span-2 bg-card border border-border rounded-xl flex flex-col overflow-hidden">
          <div className="px-4 py-2.5 border-b border-border flex items-center justify-between shrink-0">
            <span className="text-xs font-semibold">Recent Orders</span>
            <span className="text-[10px] text-muted-foreground">Today  ·  {BASE_ORDERS.length} orders</span>
          </div>
          <div className="flex-1 overflow-y-auto">
            <table className="w-full text-[11px]">
              <thead className="sticky top-0 bg-card z-10">
                <tr className="border-b border-border text-muted-foreground">
                  <th className="text-left px-4 py-1.5 font-medium">Time</th>
                  <th className="text-left px-2 py-1.5 font-medium">Security</th>
                  <th className="text-left px-2 py-1.5 font-medium">Side</th>
                  <th className="text-right px-2 py-1.5 font-medium">Size</th>
                  <th className="text-right px-2 py-1.5 font-medium">Yield/Price</th>
                  <th className="text-right px-4 py-1.5 font-medium">Status</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border">
                {recentOrders.map(o => (
                  <tr key={o.id} className="hover:bg-secondary/40 transition-colors">
                    <td className="px-4 py-1.5 text-muted-foreground font-mono">{o.time}</td>
                    <td className="px-2 py-1.5">
                      <div className="font-medium">{o.security}</div>
                      <div className="text-muted-foreground text-[10px]">{o.account}</div>
                    </td>
                    <td className="px-2 py-1.5">
                      <span className={cn('font-semibold', o.side === 'Buy' ? 'text-buy' : 'text-sell')}>{o.side}</span>
                    </td>
                    <td className="px-2 py-1.5 text-right font-mono">
                      {o.cusip.startsWith('CME') ? `${o.faceValueMM} cts` : `$${o.faceValueMM}MM`}
                    </td>
                    <td className="px-2 py-1.5 text-right font-mono text-muted-foreground">
                      {o.avgFillYield ? o.avgFillYield.toFixed(3) + '%' : o.limitPrice ? o.limitPrice.toFixed(3) : '—'}
                    </td>
                    <td className="px-4 py-1.5 text-right"><StatusBadge status={o.status} /></td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  )
}

// angular-app/src/app/trading/fi/panels/dashboard-panel.component.ts
import { Component, OnInit, OnDestroy, ChangeDetectionStrategy, ChangeDetectorRef, ViewEncapsulation } from '@angular/core'
import { CommonModule } from '@angular/common'
import { Subscription, combineLatest } from 'rxjs'
import { ChartModule } from 'primeng/chart'
import {
  MarketDataService, fmtYield, fmtBps, fmtPnL, fmtDV01,
  BASE_ORDERS, BASE_POSITIONS,
  type Treasury, type YieldCurvePoint, type CDXIndex,
} from '../market-data.service'

const TOTAL_PNL_TODAY = 93_170
const TOTAL_PNL_MTD   = 243_135
const TOTAL_PNL_YTD   = 590_320
const TOTAL_DV01       = 420_945
const TOTAL_CS01       = 57_182

@Component({
  selector: 'app-dashboard-panel',
  standalone: true,
  encapsulation: ViewEncapsulation.None,
  imports: [CommonModule, ChartModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="panel">

      <!-- KPI row -->
      <div class="kpi-row">
        <div class="kpi-card">
          <span class="kpi-label">P&amp;L Today</span>
          <span class="kpi-value" [class.buy]="true">{{ fmtPnL(TOTAL_PNL_TODAY) }}</span>
          <span class="kpi-sub">All strategies</span>
        </div>
        <div class="kpi-card">
          <span class="kpi-label">P&amp;L MTD</span>
          <span class="kpi-value buy">{{ fmtPnL(TOTAL_PNL_MTD) }}</span>
          <span class="kpi-sub">March 2026</span>
        </div>
        <div class="kpi-card">
          <span class="kpi-label">P&amp;L YTD</span>
          <span class="kpi-value buy">{{ fmtPnL(TOTAL_PNL_YTD) }}</span>
          <span class="kpi-sub">Since Jan 1</span>
        </div>
        <div class="kpi-card">
          <span class="kpi-label">Net DV01</span>
          <span class="kpi-value">{{ fmtDV01(TOTAL_DV01) }}</span>
          <span class="kpi-sub">Portfolio rate sensitivity</span>
        </div>
        <div class="kpi-card">
          <span class="kpi-label">Net CS01</span>
          <span class="kpi-value">{{ fmtDV01(TOTAL_CS01) }}</span>
          <span class="kpi-sub">Portfolio credit sensitivity</span>
        </div>
      </div>

      <!-- Middle: Yield curve + Benchmarks -->
      <div class="mid-row flex-1">

        <!-- Yield curve chart -->
        <div class="card">
          <div class="card-header">
            <div>
              <span class="card-title">US Treasury Yield Curve</span>
              <span class="card-subtitle">On-The-Run · Live</span>
            </div>
            <div class="legend-row">
              <span class="legend-item"><span class="legend-line primary"></span> Today</span>
              <span class="legend-item"><span class="legend-line muted"></span> Prev Close</span>
            </div>
          </div>
          <div class="chart-area">
            <p-chart type="line" [data]="yieldChartData" [options]="yieldChartOpts" height="100%" width="100%" />
          </div>
        </div>

        <!-- Benchmarks -->
        <div class="card">
          <div class="card-header"><span class="card-title">Key Benchmarks</span></div>
          <div class="bench-list">
            @for (b of benchmarks; track b.label) {
              <div class="bench-row">
                <span class="bench-label">{{ b.label }}</span>
                <div class="bench-right">
                  <div class="bench-val">{{ b.displayVal }}</div>
                  @if (b.change !== null) {
                    <div class="bench-chg" [class.buy]="b.change < 0" [class.sell]="b.change > 0">
                      {{ fmtBps(b.change) }}
                    </div>
                  }
                </div>
              </div>
            }
            <div class="bench-row">
              <span class="bench-label">2s10s Slope</span>
              <div class="bench-right">
                <div class="bench-val" [class.buy]="slope >= 0" [class.sell]="slope < 0">
                  {{ slope > 0 ? '+' : '' }}{{ slope }} bps
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Bottom: Positions + Orders -->
      <div class="bottom-row">

        <!-- Position summary -->
        <div class="card pos-card">
          <div class="card-header"><span class="card-title">Position Summary</span></div>
          <div class="scroll-list">
            @for (p of positions; track p.id) {
              <div class="pos-row">
                <div>
                  <div class="pos-sec" [class.buy]="p.direction === 'Long'" [class.sell]="p.direction === 'Short'">
                    {{ p.direction === 'Long' ? '▲' : '▼' }} {{ p.security }}
                  </div>
                  <div class="pos-class">{{ p.assetClass }}</div>
                </div>
                <div class="pos-right">
                  <div [class.buy]="p.pnlToday >= 0" [class.sell]="p.pnlToday < 0">{{ fmtPnL(p.pnlToday) }}</div>
                  <div class="pos-dv01">{{ fmtDV01(absNum(p.dv01)) }} dv01</div>
                </div>
              </div>
            }
          </div>
        </div>

        <!-- Recent orders -->
        <div class="card orders-card">
          <div class="card-header">
            <span class="card-title">Recent Orders</span>
            <span class="card-subtitle">Today · {{ orders.length }} orders</span>
          </div>
          <div class="table-scroll">
            <table class="orders-table">
              <thead>
                <tr>
                  <th>Time</th>
                  <th>Security</th>
                  <th>Side</th>
                  <th class="text-right">Size</th>
                  <th class="text-right">Yield/Price</th>
                  <th class="text-right">Status</th>
                </tr>
              </thead>
              <tbody>
                @for (o of recentOrders; track o.id) {
                  <tr>
                    <td class="mono muted">{{ o.time }}</td>
                    <td>
                      <div class="sec-name">{{ o.security }}</div>
                      <div class="sec-acct">{{ o.account }}</div>
                    </td>
                    <td class="side" [class.buy]="o.side === 'Buy'" [class.sell]="o.side === 'Sell'">{{ o.side }}</td>
                    <td class="text-right mono">{{ o.cusip.startsWith('CME') ? o.faceValueMM + ' cts' : '$' + o.faceValueMM + 'MM' }}</td>
                    <td class="text-right mono muted">{{ o.avgFillYield ? o.avgFillYield.toFixed(3) + '%' : o.limitPrice ? o.limitPrice.toFixed(3) : '—' }}</td>
                    <td class="text-right"><span class="status-badge" [ngClass]="statusClass(o.status)">{{ o.status }}</span></td>
                  </tr>
                }
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    :host { display: flex; flex-direction: column; height: 100%; overflow: hidden; }
    .panel { height: 100%; display: flex; flex-direction: column; gap: 0.75rem; padding: 0.75rem; overflow: hidden; }
    .flex-1 { flex: 1; min-height: 0; }

    .kpi-row { display: grid; grid-template-columns: repeat(5, 1fr); gap: 0.5rem; flex-shrink: 0; }
    .kpi-card { background: var(--ds-card); border: 1px solid var(--ds-border); border-radius: 12px; padding: 0.75rem 1rem; display: flex; flex-direction: column; gap: 2px; }
    .kpi-label { font-size: 10px; color: var(--ds-muted-foreground); text-transform: uppercase; letter-spacing: 0.08em; }
    .kpi-value { font-size: 1.2rem; font-weight: 600; font-family: var(--ds-font-mono); line-height: 1.2; margin-top: 2px; color: var(--ds-foreground); }
    .kpi-value.buy { color: var(--ds-buy); }
    .kpi-value.sell { color: var(--ds-sell); }
    .kpi-sub { font-size: 10px; color: var(--ds-muted-foreground); }

    .mid-row { display: grid; grid-template-columns: 2fr 1fr; grid-template-rows: 1fr; gap: 0.75rem; flex: 1; min-height: 0; height: 100%; }
    .bottom-row { display: grid; grid-template-columns: 1fr 2fr; gap: 0.75rem; height: 210px; flex-shrink: 0; }

    .card { background: var(--ds-card); border: 1px solid var(--ds-border); border-radius: 12px; display: flex; flex-direction: column; overflow: hidden; }
    .pos-card { }
    .orders-card { }

    .card-header { display: flex; align-items: center; justify-content: space-between; padding: 0.625rem 1rem; border-bottom: 1px solid var(--ds-border); flex-shrink: 0; }
    .card-title { font-size: 0.75rem; font-weight: 600; }
    .card-subtitle { font-size: 10px; color: var(--ds-muted-foreground); margin-left: 0.5rem; }
    .legend-row { display: flex; align-items: center; gap: 0.75rem; font-size: 10px; color: var(--ds-muted-foreground); }
    .legend-item { display: flex; align-items: center; gap: 4px; }
    .legend-line { display: inline-block; width: 12px; height: 2px; border-radius: 1px; }
    .legend-line.primary { background: var(--ds-primary); }
    .legend-line.muted { background: var(--ds-muted-foreground); opacity: 0.5; }

    .chart-area { flex: 1; padding: 0.5rem; min-height: 0; display: flex; align-items: stretch; }
    .chart-area p-chart, .chart-area ::ng-deep canvas { width: 100% !important; height: 100% !important; }

    .bench-list { display: flex; flex-direction: column; flex: 1; overflow-y: auto; }
    .bench-row { display: flex; align-items: center; justify-content: space-between; padding: 0.625rem 1rem; border-bottom: 1px solid var(--ds-border); }
    .bench-row:last-child { border-bottom: none; }
    .bench-label { font-size: 12px; color: var(--ds-muted-foreground); font-family: var(--ds-font-mono); }
    .bench-right { text-align: right; }
    .bench-val { font-size: 0.875rem; font-family: var(--ds-font-mono); font-weight: 600; }
    .bench-chg { font-size: 10px; font-family: var(--ds-font-mono); }

    .scroll-list { flex: 1; overflow-y: auto; }
    .pos-row { display: flex; align-items: center; justify-content: space-between; padding: 0.375rem 1rem; font-size: 11px; border-bottom: 1px solid var(--ds-border); }
    .pos-sec { font-weight: 500; }
    .pos-class { color: var(--ds-muted-foreground); font-size: 10px; }
    .pos-right { text-align: right; font-family: var(--ds-font-mono); }
    .pos-dv01 { font-size: 10px; color: var(--ds-muted-foreground); }

    .table-scroll { flex: 1; overflow-y: auto; }
    .orders-table { width: 100%; font-size: 11px; border-collapse: collapse; }
    .orders-table thead tr { border-bottom: 1px solid var(--ds-border); position: sticky; top: 0; background: var(--ds-card); z-index: 1; }
    .orders-table th { padding: 0.375rem 0.5rem; font-weight: 500; color: var(--ds-muted-foreground); text-align: left; }
    .orders-table td { padding: 0.375rem 0.5rem; border-bottom: 1px solid var(--ds-border); }
    .text-right { text-align: right !important; }
    .mono { font-family: var(--ds-font-mono); }
    .muted { color: var(--ds-muted-foreground); }
    .side { font-weight: 600; }

    .sec-name { font-weight: 500; }
    .sec-acct { font-size: 10px; color: var(--ds-muted-foreground); }

    .status-badge { font-size: 10px; padding: 2px 6px; border-radius: 9999px; font-weight: 500; }
    .status-filled    { background: rgba(0,163,108,0.15); color: var(--ds-buy); }
    .status-working   { background: rgba(22,82,240,0.15); color: var(--ds-primary); }
    .status-partial   { background: rgba(217,119,6,0.15); color: var(--ds-warning); }
    .status-cancelled { background: var(--ds-secondary); color: var(--ds-muted-foreground); }

    .buy  { color: var(--ds-buy); }
    .sell { color: var(--ds-sell); }
  `],
})
export class DashboardPanelComponent implements OnInit, OnDestroy {
  readonly TOTAL_PNL_TODAY = TOTAL_PNL_TODAY
  readonly TOTAL_PNL_MTD   = TOTAL_PNL_MTD
  readonly TOTAL_PNL_YTD   = TOTAL_PNL_YTD
  readonly TOTAL_DV01       = TOTAL_DV01
  readonly TOTAL_CS01       = TOTAL_CS01
  readonly positions = BASE_POSITIONS
  readonly orders = BASE_ORDERS
  readonly recentOrders = [...BASE_ORDERS].slice(-6).reverse()

  readonly fmtPnL = fmtPnL
  readonly fmtDV01 = fmtDV01
  readonly fmtBps = fmtBps
  readonly fmtYield = fmtYield
  readonly absNum = Math.abs

  slope = 0
  benchmarks: { label: string; displayVal: string; change: number | null }[] = []
  yieldChartData: any = {}
  yieldChartOpts: any = {}

  private subs = new Subscription()

  constructor(
    private marketData: MarketDataService,
    private cdr: ChangeDetectorRef,
  ) {}

  ngOnInit(): void {
    this.buildChartOpts()

    this.subs.add(this.marketData.treasuries$.subscribe(t => {
      const tsy2Y  = t.find(x => x.tenor === '2Y')
      const tsy10Y = t.find(x => x.tenor === '10Y')
      const tsy30Y = t.find(x => x.tenor === '30Y')
      this.slope = tsy2Y && tsy10Y ? Math.round((tsy10Y.bidYield - tsy2Y.bidYield) * 100) : -34
      this.cdr.markForCheck()
    }))

    this.subs.add(this.marketData.yieldCurve$.subscribe(yc => {
      this.buildChart(yc)
      this.cdr.markForCheck()
    }))

    this.subs.add(combineLatest([this.marketData.treasuries$, this.marketData.cdxIndices$]).subscribe(([t, idx]) => {
      this.updateBenchmarks(t, idx)
      this.cdr.markForCheck()
    }))
  }

  private updateBenchmarks(t: Treasury[], idx: CDXIndex[]): void {
    const tsy2Y  = t.find(x => x.tenor === '2Y')
    const tsy10Y = t.find(x => x.tenor === '10Y')
    const tsy30Y = t.find(x => x.tenor === '30Y')
    const ig = idx.find(c => c.name.includes('NA.IG') && c.tenor === '5Y')
    const hy = idx.find(c => c.name.includes('NA.HY'))
    this.benchmarks = [
      { label: '2Y  UST', displayVal: tsy2Y  ? fmtYield(tsy2Y.bidYield)  : '—', change: tsy2Y?.change  ?? null },
      { label: '10Y UST', displayVal: tsy10Y ? fmtYield(tsy10Y.bidYield) : '—', change: tsy10Y?.change ?? null },
      { label: '30Y UST', displayVal: tsy30Y ? fmtYield(tsy30Y.bidYield) : '—', change: tsy30Y?.change ?? null },
      { label: 'CDX IG',  displayVal: ig ? ((ig.bidSpread + ig.askSpread) / 2).toFixed(1) + ' bps' : '—',  change: ig?.change  ?? null },
      { label: 'CDX HY',  displayVal: hy ? ((hy.bidSpread + hy.askSpread) / 2).toFixed(0) + ' bps' : '—', change: hy?.change ?? null },
    ]
  }

  private buildChart(yc: any[]): void {
    this.yieldChartData = {
      labels: yc.map(p => p.tenor),
      datasets: [
        {
          label: 'Today',
          data: yc.map(p => p.yield),
          borderColor: 'var(--ds-primary)',
          backgroundColor: 'rgba(22,82,240,0.1)',
          borderWidth: 2,
          tension: 0.4,
          fill: true,
          pointRadius: 3,
          pointBackgroundColor: 'var(--ds-primary)',
        },
        {
          label: 'Prev Close',
          data: yc.map(p => p.prevYield),
          borderColor: 'var(--ds-muted-foreground)',
          backgroundColor: 'transparent',
          borderWidth: 1,
          borderDash: [3, 3],
          tension: 0.4,
          fill: false,
          pointRadius: 0,
        },
      ],
    }
  }

  private buildChartOpts(): void {
    this.yieldChartOpts = {
      responsive: true,
      maintainAspectRatio: false,
      animation: false,
      plugins: {
        legend: { display: false },
        tooltip: {
          callbacks: { label: (ctx: any) => ctx.parsed.y.toFixed(3) + '%' },
        },
      },
      scales: {
        x: { ticks: { font: { size: 9 }, color: 'var(--ds-muted-foreground)' }, grid: { color: 'rgba(0,0,0,0.05)' } },
        y: { ticks: { font: { size: 9 }, color: 'var(--ds-muted-foreground)', callback: (v: number) => v.toFixed(1) + '%' }, grid: { color: 'rgba(0,0,0,0.05)' } },
      },
    }
  }

  statusClass(status: string): string {
    const map: Record<string, string> = {
      Filled: 'status-filled', Working: 'status-working',
      Partial: 'status-partial', Cancelled: 'status-cancelled',
    }
    return map[status] ?? 'status-cancelled'
  }

  ngOnDestroy(): void {
    this.subs.unsubscribe()
  }
}
