// react-app/src/components/trading/fi/PositionsPanel.tsx
import { useMemo, useState, useCallback } from 'react'
import { AgGridReact } from 'ag-grid-react'
import { AllEnterpriseModule } from 'ag-grid-enterprise'
import type { ColDef, ICellRendererParams, RowClickedEvent, GridReadyEvent } from 'ag-grid-community'
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Cell, ReferenceLine } from 'recharts'
import { cn } from '@/lib/utils'
import { BASE_POSITIONS, fmtPnL, fmtDV01, fmtPrice, fmtYield, type Position } from './marketData'
import { marketsUITheme } from './agGridTheme'

// ── Derived totals ─────────────────────────────────────────────────────────────

const totalPnlToday = BASE_POSITIONS.reduce((s, p) => s + p.pnlToday, 0)
const totalPnlMtd   = BASE_POSITIONS.reduce((s, p) => s + p.pnlMtd,   0)
const totalPnlYtd   = BASE_POSITIONS.reduce((s, p) => s + p.pnlYtd,   0)
const totalDV01     = BASE_POSITIONS.reduce((s, p) => s + p.dv01, 0)
const totalCS01     = BASE_POSITIONS.reduce((s, p) => s + p.cs01, 0)
const totalMktVal   = BASE_POSITIONS.filter(p => p.marketValueMM !== 0).reduce((s, p) => s + p.marketValueMM, 0)

const DV01_BY_CLASS = [
  { label: 'Treasury',  dv01: BASE_POSITIONS.filter(p => p.assetClass === 'Treasury').reduce((s, p) => s + p.dv01, 0) },
  { label: 'Corporate', dv01: BASE_POSITIONS.filter(p => p.assetClass === 'Corporate').reduce((s, p) => s + p.dv01, 0) },
  { label: 'Futures',   dv01: BASE_POSITIONS.filter(p => p.assetClass === 'Future').reduce((s, p) => s + p.dv01, 0) },
  { label: 'CDS',       dv01: BASE_POSITIONS.filter(p => p.assetClass === 'CDS').reduce((s, p) => s + p.dv01, 0) },
]

// ── Cell renderers ────────────────────────────────────────────────────────────

const DirectionRenderer = ({ value }: ICellRendererParams) => (
  <span className={cn(
    'text-[10px] px-2 py-0.5 rounded-full font-semibold tracking-wide',
    value === 'Long' ? 'bg-buy/15 text-buy' : 'bg-sell/15 text-sell',
  )}>
    {value === 'Long' ? 'LONG' : 'SHORT'}
  </span>
)

const AssetClassRenderer = ({ value }: ICellRendererParams) => {
  const colors: Record<string, string> = {
    Treasury: 'text-primary', Corporate: 'text-buy', Future: 'text-warning', CDS: 'text-sell',
  }
  return <span className={cn('text-[10px] font-medium', colors[value] ?? 'text-muted-foreground')}>{value}</span>
}

const SecurityRenderer = ({ data }: ICellRendererParams<Position>) => (
  <div className="flex flex-col justify-center h-full leading-none gap-0.5">
    <div className="font-semibold text-[11px]">{data?.security}</div>
    <div className="text-[10px] text-muted-foreground font-mono">{data?.cusip}</div>
  </div>
)

const PnlRenderer = ({ value }: ICellRendererParams) => (
  <span className={cn('font-mono font-semibold', value >= 0 ? 'text-buy' : 'text-sell')}>{fmtPnL(value)}</span>
)

const PnlMutedRenderer = ({ value }: ICellRendererParams) => (
  <span className={cn('font-mono', value >= 0 ? 'text-buy' : 'text-sell')}>{fmtPnL(value)}</span>
)

// ── KPI card ──────────────────────────────────────────────────────────────────

function KpiCard({ label, value, sub, valueClass }: { label: string; value: string; sub?: string; valueClass?: string }) {
  return (
    <div className="bg-card border border-border rounded-xl px-4 py-3 flex flex-col gap-0.5">
      <span className="text-[10px] text-muted-foreground uppercase tracking-widest">{label}</span>
      <span className={cn('text-xl font-semibold font-mono leading-tight mt-0.5', valueClass)}>{value}</span>
      {sub && <span className="text-[10px] text-muted-foreground mt-0.5">{sub}</span>}
    </div>
  )
}

// ── Component ─────────────────────────────────────────────────────────────────

type AssetFilter = 'All' | 'Treasury' | 'Corporate' | 'Future' | 'CDS'
const ASSET_FILTERS: AssetFilter[] = ['All', 'Treasury', 'Corporate', 'Future', 'CDS']

export function PositionsPanel() {
  const [assetFilter, setAssetFilter] = useState<AssetFilter>('All')
  const [selected, setSelected] = useState<Position | null>(null)

  const rowData = useMemo(() =>
    assetFilter === 'All' ? BASE_POSITIONS : BASE_POSITIONS.filter(p => p.assetClass === assetFilter),
    [assetFilter],
  )

  const colDefs = useMemo<ColDef<Position>[]>(() => [
    {
      field: 'security',
      headerName: 'Security',
      width: 160,
      cellRenderer: SecurityRenderer,
      filter: 'agTextColumnFilter',
      pinned: 'left',
    },
    {
      field: 'assetClass',
      headerName: 'Class',
      width: 82,
      cellRenderer: AssetClassRenderer,
      filter: 'agSetColumnFilter',
    },
    {
      field: 'direction',
      headerName: 'Side',
      width: 78,
      cellRenderer: DirectionRenderer,
      filter: 'agSetColumnFilter',
    },
    {
      field: 'faceValueMM',
      headerName: 'Size',
      width: 78,
      type: 'numericColumn',
      cellClass: 'font-mono font-semibold',
      valueFormatter: p => p.data?.assetClass === 'Future' ? `${p.value} cts` : `$${p.value}MM`,
    },
    {
      field: 'avgPrice',
      headerName: 'Avg Px',
      width: 72,
      type: 'numericColumn',
      cellClass: 'font-mono text-muted-foreground',
      valueFormatter: p => fmtPrice(p.value),
    },
    {
      field: 'currentPrice',
      headerName: 'Curr Px',
      width: 72,
      type: 'numericColumn',
      cellClass: 'font-mono',
      valueFormatter: p => fmtPrice(p.value),
    },
    {
      field: 'currentYield',
      headerName: 'Curr Yld',
      width: 76,
      type: 'numericColumn',
      cellClass: 'font-mono text-muted-foreground',
      valueFormatter: p => p.value > 0 ? fmtYield(p.value) : '—',
    },
    {
      field: 'dv01',
      headerName: 'DV01',
      width: 76,
      type: 'numericColumn',
      cellClass: 'font-mono',
      valueFormatter: p => fmtDV01(p.value),
      cellStyle: p => ({ color: p.value >= 0 ? undefined : 'var(--color-sell)' }),
    },
    {
      field: 'cs01',
      headerName: 'CS01',
      width: 72,
      type: 'numericColumn',
      cellClass: 'font-mono text-muted-foreground',
      valueFormatter: p => p.value > 0 ? fmtDV01(p.value) : '—',
    },
    {
      field: 'pnlToday',
      headerName: 'P&L Today',
      width: 90,
      type: 'numericColumn',
      cellRenderer: PnlRenderer,
      filter: 'agNumberColumnFilter',
    },
    {
      field: 'pnlMtd',
      headerName: 'P&L MTD',
      width: 88,
      type: 'numericColumn',
      cellRenderer: PnlMutedRenderer,
      filter: 'agNumberColumnFilter',
    },
    {
      field: 'pnlYtd',
      headerName: 'P&L YTD',
      width: 88,
      type: 'numericColumn',
      cellRenderer: PnlMutedRenderer,
      filter: 'agNumberColumnFilter',
    },
  ], [])

  const defaultColDef = useMemo<ColDef>(() => ({
    sortable: true,
    resizable: true,
    minWidth: 50,
  }), [])

  const onRowClicked = useCallback((e: RowClickedEvent<Position>) => {
    setSelected(prev => prev?.id === e.data?.id ? null : (e.data ?? null))
  }, [])

  const onGridReady = useCallback((e: GridReadyEvent) => {
    e.api.sizeColumnsToFit()
  }, [])

  return (
    <div className="h-full flex flex-col overflow-hidden">
      {/* KPI row */}
      <div className="grid grid-cols-6 gap-2 p-3 shrink-0">
        <KpiCard label="P&L Today"    value={fmtPnL(totalPnlToday)}              valueClass={totalPnlToday >= 0 ? 'text-buy' : 'text-sell'} />
        <KpiCard label="P&L MTD"      value={fmtPnL(totalPnlMtd)}                valueClass={totalPnlMtd   >= 0 ? 'text-buy' : 'text-sell'} />
        <KpiCard label="P&L YTD"      value={fmtPnL(totalPnlYtd)}                valueClass={totalPnlYtd   >= 0 ? 'text-buy' : 'text-sell'} />
        <KpiCard label="Net DV01"     value={fmtDV01(totalDV01)}                 sub="Rate sensitivity" />
        <KpiCard label="Net CS01"     value={fmtDV01(totalCS01)}                 sub="Credit sensitivity" />
        <KpiCard label="Market Value" value={'$' + totalMktVal.toFixed(1) + 'MM'} sub="Long positions" />
      </div>

      {/* Main content */}
      <div className="flex-1 min-h-0 flex gap-3 px-3 pb-3 overflow-hidden">

        {/* Positions grid */}
        <div className="flex-1 min-w-0 flex flex-col overflow-hidden">
          {/* Filter toolbar */}
          <div className="flex items-center justify-between mb-2 shrink-0">
            <div className="flex items-center gap-1">
              {ASSET_FILTERS.map(f => (
                <button
                  key={f}
                  onClick={() => setAssetFilter(f)}
                  className={cn(
                    'px-2.5 py-1 rounded-md text-xs font-medium transition-colors',
                    assetFilter === f ? 'bg-accent text-foreground' : 'text-muted-foreground hover:text-foreground hover:bg-secondary',
                  )}
                >
                  {f}
                </button>
              ))}
            </div>
            <span className="text-[11px] text-muted-foreground">{rowData.length} positions · All strategies</span>
          </div>
          <div className="flex-1 min-h-0">
            <AgGridReact<Position>
              theme={marketsUITheme}
              modules={[AllEnterpriseModule]}
              rowData={rowData}
              columnDefs={colDefs}
              defaultColDef={defaultColDef}
              rowHeight={40}
              headerHeight={30}
              rowSelection={{ mode: 'singleRow', checkboxes: false, enableClickSelection: true }}
              onRowClicked={onRowClicked}
              onGridReady={onGridReady}
              sideBar={{ toolPanels: ['columns', 'filters'], hiddenByDefault: true }}
              pinnedBottomRowData={[{
                id: 'total', security: 'TOTAL', assetClass: '', direction: '',
                faceValueMM: 0, avgPrice: 0, currentPrice: 0, currentYield: 0,
                dv01: totalDV01, cs01: totalCS01,
                pnlToday: totalPnlToday, pnlMtd: totalPnlMtd, pnlYtd: totalPnlYtd,
                cusip: '', marketValueMM: 0,
              } as unknown as Position]}
              suppressCellFocus
              enableCellTextSelection
              style={{ height: '100%', width: '100%' }}
            />
          </div>
        </div>

        {/* Right sidebar: DV01 chart + detail/attribution */}
        <div className="w-56 flex flex-col gap-3 shrink-0">
          <div className="bg-card border border-border rounded-xl overflow-hidden shrink-0">
            <div className="px-4 py-2.5 border-b border-border">
              <span className="text-xs font-semibold">DV01 by Class</span>
            </div>
            <div className="p-2 h-36">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={DV01_BY_CLASS} layout="vertical" margin={{ top: 2, right: 12, left: 0, bottom: 2 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="var(--color-border)" strokeOpacity={0.4} horizontal={false} />
                  <XAxis type="number" tick={{ fontSize: 9, fill: 'var(--color-muted-foreground)' }} axisLine={false} tickLine={false} tickFormatter={v => '$' + (v / 1000).toFixed(0) + 'K'} />
                  <YAxis type="category" dataKey="label" tick={{ fontSize: 10, fill: 'var(--color-muted-foreground)' }} axisLine={false} tickLine={false} width={56} />
                  <Tooltip contentStyle={{ background: 'var(--color-card)', border: '1px solid var(--color-border)', borderRadius: 4, fontSize: 11 }} formatter={(v: number) => ['$' + Math.abs(v).toLocaleString(), 'DV01']} />
                  <ReferenceLine x={0} stroke="var(--color-border)" />
                  <Bar dataKey="dv01" radius={[0, 3, 3, 0]}>
                    {DV01_BY_CLASS.map((d, i) => <Cell key={i} fill={d.dv01 >= 0 ? 'var(--color-buy)' : 'var(--color-sell)'} fillOpacity={0.7} />)}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>

          {selected ? (
            <div className="bg-card border border-border rounded-xl overflow-hidden flex-1 min-h-0 flex flex-col">
              <div className="px-4 py-3 border-b border-border shrink-0">
                <div className="font-semibold text-sm">{selected.security}</div>
                <div className="text-[10px] text-muted-foreground font-mono mt-0.5">{selected.cusip}</div>
              </div>
              <div className={cn('mx-3 mt-3 px-3 py-2.5 rounded-lg shrink-0', selected.pnlToday >= 0 ? 'bg-buy/10' : 'bg-sell/10')}>
                <div className="text-[10px] text-muted-foreground uppercase tracking-wider mb-0.5">P&L Today</div>
                <div className={cn('text-xl font-semibold font-mono', selected.pnlToday >= 0 ? 'text-buy' : 'text-sell')}>{fmtPnL(selected.pnlToday)}</div>
              </div>
              <div className="flex-1 overflow-y-auto px-3 py-3">
                <div className="grid grid-cols-2 gap-x-2 gap-y-3 text-[11px]">
                  {([
                    ['Side',    selected.direction],
                    ['Class',   selected.assetClass],
                    ['Size',    selected.assetClass === 'Future' ? `${selected.faceValueMM} cts` : `$${selected.faceValueMM}MM`],
                    ['Avg Px',  fmtPrice(selected.avgPrice)],
                    ['Curr Px', fmtPrice(selected.currentPrice)],
                    ['Yield',   selected.currentYield > 0 ? fmtYield(selected.currentYield) : '—'],
                    ['DV01',    fmtDV01(selected.dv01)],
                    ['CS01',    selected.cs01 > 0 ? fmtDV01(selected.cs01) : '—'],
                    ['MTD',     fmtPnL(selected.pnlMtd)],
                    ['YTD',     fmtPnL(selected.pnlYtd)],
                  ] as [string, string][]).map(([k, v]) => (
                    <div key={k}>
                      <div className="text-[9px] text-muted-foreground uppercase tracking-wide mb-0.5">{k}</div>
                      <div className="font-mono font-medium">{v}</div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          ) : (
            <div className="bg-card border border-border rounded-xl overflow-hidden flex-1 min-h-0 flex flex-col">
              <div className="px-4 py-2.5 border-b border-border shrink-0">
                <span className="text-xs font-semibold">P&L Attribution</span>
              </div>
              <div className="flex-1 overflow-y-auto divide-y divide-border">
                {[...BASE_POSITIONS].sort((a, b) => b.pnlToday - a.pnlToday).map(p => (
                  <div key={p.id} className="flex items-center justify-between px-4 py-2 text-[11px]">
                    <span className="text-muted-foreground truncate mr-2">{p.security}</span>
                    <div className="flex items-center gap-2 shrink-0">
                      <div className="w-12 h-1 bg-secondary rounded-full overflow-hidden">
                        <div className={cn('h-full rounded-full', p.pnlToday >= 0 ? 'bg-buy' : 'bg-sell')} style={{ width: Math.min(Math.abs(p.pnlToday) / 45000 * 100, 100) + '%' }} />
                      </div>
                      <span className={cn('font-mono font-semibold w-16 text-right', p.pnlToday >= 0 ? 'text-buy' : 'text-sell')}>{fmtPnL(p.pnlToday)}</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

// angular-app/src/app/trading/fi/panels/positions-panel.component.ts
import { Component, OnInit, ChangeDetectionStrategy, ChangeDetectorRef, ViewEncapsulation } from '@angular/core'
import { CommonModule } from '@angular/common'
import { AgGridAngular } from 'ag-grid-angular'
import { AllEnterpriseModule, ModuleRegistry } from 'ag-grid-enterprise'
import type { ColDef, RowClickedEvent, GridReadyEvent } from 'ag-grid-community'
import { ChartModule } from 'primeng/chart'
import { marketsUITheme } from '../ag-grid-theme'
import { BASE_POSITIONS, fmtPnL, fmtDV01, fmtPrice, fmtYield, type Position } from '../market-data.service'

ModuleRegistry.registerModules([AllEnterpriseModule])

type AssetFilter = 'All' | 'Treasury' | 'Corporate' | 'Future' | 'CDS'
const ASSET_FILTERS: AssetFilter[] = ['All', 'Treasury', 'Corporate', 'Future', 'CDS']

const totalPnlToday = BASE_POSITIONS.reduce((s, p) => s + p.pnlToday, 0)
const totalPnlMtd   = BASE_POSITIONS.reduce((s, p) => s + p.pnlMtd,   0)
const totalPnlYtd   = BASE_POSITIONS.reduce((s, p) => s + p.pnlYtd,   0)
const totalDV01     = BASE_POSITIONS.reduce((s, p) => s + p.dv01, 0)
const totalCS01     = BASE_POSITIONS.reduce((s, p) => s + p.cs01, 0)
const totalMktVal   = BASE_POSITIONS.filter(p => p.marketValueMM !== 0).reduce((s, p) => s + p.marketValueMM, 0)

const DV01_BY_CLASS = [
  { label: 'Treasury',  dv01: BASE_POSITIONS.filter(p => p.assetClass === 'Treasury').reduce((s, p) => s + p.dv01, 0) },
  { label: 'Corporate', dv01: BASE_POSITIONS.filter(p => p.assetClass === 'Corporate').reduce((s, p) => s + p.dv01, 0) },
  { label: 'Futures',   dv01: BASE_POSITIONS.filter(p => p.assetClass === 'Future').reduce((s, p) => s + p.dv01, 0) },
  { label: 'CDS',       dv01: BASE_POSITIONS.filter(p => p.assetClass === 'CDS').reduce((s, p) => s + p.dv01, 0) },
]

@Component({
  selector: 'app-positions-panel',
  standalone: true,
  encapsulation: ViewEncapsulation.None,
  imports: [CommonModule, AgGridAngular, ChartModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="panel">

      <!-- KPI row -->
      <div class="kpi-row">
        <div class="kpi-card"><span class="kpi-label">P&amp;L Today</span><span class="kpi-value" [class.buy]="totalPnlToday >= 0" [class.sell]="totalPnlToday < 0">{{ fmtPnL(totalPnlToday) }}</span></div>
        <div class="kpi-card"><span class="kpi-label">P&amp;L MTD</span><span class="kpi-value" [class.buy]="totalPnlMtd >= 0" [class.sell]="totalPnlMtd < 0">{{ fmtPnL(totalPnlMtd) }}</span></div>
        <div class="kpi-card"><span class="kpi-label">P&amp;L YTD</span><span class="kpi-value" [class.buy]="totalPnlYtd >= 0" [class.sell]="totalPnlYtd < 0">{{ fmtPnL(totalPnlYtd) }}</span></div>
        <div class="kpi-card"><span class="kpi-label">Net DV01</span><span class="kpi-value">{{ fmtDV01(totalDV01) }}</span><span class="kpi-sub">Rate sensitivity</span></div>
        <div class="kpi-card"><span class="kpi-label">Net CS01</span><span class="kpi-value">{{ fmtDV01(totalCS01) }}</span><span class="kpi-sub">Credit sensitivity</span></div>
        <div class="kpi-card"><span class="kpi-label">Market Value</span><span class="kpi-value">{{ '$' + totalMktVal.toFixed(1) + 'MM' }}</span><span class="kpi-sub">Long positions</span></div>
      </div>

      <!-- Main content -->
      <div class="main-content">

        <!-- Grid -->
        <div class="grid-col">
          <div class="filter-bar">
            <div class="filter-btns">
              @for (f of assetFilters; track f) {
                <button class="filter-btn" [class.active]="assetFilter === f" (click)="setFilter(f)">{{ f }}</button>
              }
            </div>
            <span class="muted small">{{ rowData.length }} positions · All strategies</span>
          </div>
          <div class="flex-1">
            <ag-grid-angular
              [theme]="theme" [rowData]="rowData" [columnDefs]="colDefs" [defaultColDef]="defaultColDef"
              [rowHeight]="40" [headerHeight]="30" [rowSelection]="rowSel" (rowClicked)="onRowClicked($event)"
              (gridReady)="onGridReady($event)" [suppressCellFocus]="true" [enableCellTextSelection]="true"
              [pinnedBottomRowData]="pinnedRow" [sideBar]="sideBar" style="height:100%;width:100%"
            />
          </div>
        </div>

        <!-- Right sidebar -->
        <div class="sidebar">

          <!-- DV01 chart -->
          <div class="card shrink-0">
            <div class="card-header"><span class="card-title">DV01 by Class</span></div>
            <div style="height:9rem;padding:0.5rem">
              <p-chart type="bar" [data]="dv01ChartData" [options]="dv01ChartOpts" height="100%" width="100%" />
            </div>
          </div>

          <!-- Detail or Attribution -->
          <div class="card flex-1">
            @if (selected) {
              <div class="card-header">
                <div>
                  <div class="card-title">{{ selected.security }}</div>
                  <div class="card-subtitle">{{ selected.cusip }}</div>
                </div>
              </div>
              <div class="pnl-box" [class.buy-box]="selected.pnlToday >= 0" [class.sell-box]="selected.pnlToday < 0">
                <div class="pnl-label">P&amp;L Today</div>
                <div class="pnl-value" [class.buy]="selected.pnlToday >= 0" [class.sell]="selected.pnlToday < 0">{{ fmtPnL(selected.pnlToday) }}</div>
              </div>
              <div class="detail-grid">
                @for (row of detailRows; track row[0]) {
                  <div class="detail-field">
                    <div class="detail-label">{{ row[0] }}</div>
                    <div class="detail-val mono">{{ row[1] }}</div>
                  </div>
                }
              </div>
            } @else {
              <div class="card-header"><span class="card-title">P&amp;L Attribution</span></div>
              <div class="attrib-list">
                @for (p of sortedPositions; track p.id) {
                  <div class="attrib-row">
                    <span class="muted truncate">{{ p.security }}</span>
                    <div class="attrib-right">
                      <div class="attrib-bar">
                        <div class="attrib-fill" [class.buy-fill]="p.pnlToday >= 0" [class.sell-fill]="p.pnlToday < 0" [style.width.%]="barPct(p.pnlToday)"></div>
                      </div>
                      <span class="mono semibold w16" [class.buy]="p.pnlToday >= 0" [class.sell]="p.pnlToday < 0">{{ fmtPnL(p.pnlToday) }}</span>
                    </div>
                  </div>
                }
              </div>
            }
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    :host { display: flex; flex-direction: column; height: 100%; overflow: hidden; }
    .panel { height: 100%; display: flex; flex-direction: column; overflow: hidden; }
    .flex-1 { flex: 1; min-height: 0; }

    .kpi-row { display: grid; grid-template-columns: repeat(6, 1fr); gap: 0.5rem; padding: 0.75rem; flex-shrink: 0; }
    .kpi-card { background: var(--ds-card); border: 1px solid var(--ds-border); border-radius: 12px; padding: 0.75rem 1rem; display: flex; flex-direction: column; gap: 2px; }
    .kpi-label { font-size: 10px; color: var(--ds-muted-foreground); text-transform: uppercase; letter-spacing: 0.08em; }
    .kpi-value { font-size: 1.1rem; font-weight: 600; font-family: var(--ds-font-mono); line-height: 1.2; }
    .kpi-sub   { font-size: 10px; color: var(--ds-muted-foreground); }

    .main-content { flex: 1; min-height: 0; display: flex; gap: 0.75rem; padding: 0 0.75rem 0.75rem; overflow: hidden; }
    .grid-col { flex: 1; min-width: 0; display: flex; flex-direction: column; overflow: hidden; }
    .filter-bar { display: flex; align-items: center; justify-content: space-between; margin-bottom: 0.5rem; flex-shrink: 0; }
    .filter-btns { display: flex; gap: 4px; }
    .filter-btn { padding: 0.25rem 0.625rem; border-radius: 6px; font-size: 0.75rem; font-weight: 500; background: none; border: none; color: var(--ds-muted-foreground); cursor: pointer; }
    .filter-btn.active { background: var(--ds-accent); color: var(--ds-foreground); }

    .sidebar { width: 14rem; display: flex; flex-direction: column; gap: 0.75rem; flex-shrink: 0; overflow: hidden; }
    .card { background: var(--ds-card); border: 1px solid var(--ds-border); border-radius: 12px; display: flex; flex-direction: column; overflow: hidden; }
    .shrink-0 { flex-shrink: 0; }
    .card-header { padding: 0.625rem 1rem; border-bottom: 1px solid var(--ds-border); flex-shrink: 0; }
    .card-title { font-size: 0.75rem; font-weight: 600; }
    .card-subtitle { font-size: 10px; color: var(--ds-muted-foreground); font-family: var(--ds-font-mono); }

    .pnl-box { margin: 0.75rem; padding: 0.625rem 0.75rem; border-radius: 8px; flex-shrink: 0; }
    .buy-box  { background: rgba(0,163,108,0.1); }
    .sell-box { background: rgba(207,32,47,0.1); }
    .pnl-label { font-size: 10px; text-transform: uppercase; letter-spacing: 0.06em; color: var(--ds-muted-foreground); margin-bottom: 2px; }
    .pnl-value { font-size: 1.2rem; font-weight: 600; font-family: var(--ds-font-mono); }

    .detail-grid { padding: 0.75rem; display: grid; grid-template-columns: 1fr 1fr; gap: 0.75rem 0.5rem; flex: 1; overflow-y: auto; }
    .detail-field .detail-label { font-size: 9px; text-transform: uppercase; letter-spacing: 0.04em; color: var(--ds-muted-foreground); margin-bottom: 2px; }
    .detail-field .detail-val { font-weight: 500; }

    .attrib-list { flex: 1; overflow-y: auto; }
    .attrib-row { display: flex; align-items: center; justify-content: space-between; padding: 0.5rem 1rem; font-size: 11px; border-bottom: 1px solid var(--ds-border); }
    .attrib-right { display: flex; align-items: center; gap: 0.5rem; flex-shrink: 0; }
    .attrib-bar { width: 3rem; height: 4px; background: var(--ds-secondary); border-radius: 9999px; overflow: hidden; }
    .attrib-fill { height: 100%; border-radius: 9999px; }
    .buy-fill { background: var(--ds-buy); }
    .sell-fill { background: var(--ds-sell); }
    .w16 { width: 4rem; text-align: right; }
    .truncate { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; max-width: 5rem; }

    .muted { color: var(--ds-muted-foreground); }
    .small { font-size: 10px; }
    .mono  { font-family: var(--ds-font-mono); }
    .semibold { font-weight: 600; }
    .buy  { color: var(--ds-buy); }
    .sell { color: var(--ds-sell); }
  `],
})
export class PositionsPanelComponent implements OnInit {
  readonly theme = marketsUITheme
  readonly rowSel = { mode: 'singleRow' as const, checkboxes: false, enableClickSelection: true }
  readonly assetFilters = ASSET_FILTERS
  readonly sideBar = { toolPanels: ['columns', 'filters'], hiddenByDefault: true }
  readonly fmtPnL = fmtPnL
  readonly fmtDV01 = fmtDV01
  readonly totalPnlToday = totalPnlToday
  readonly totalPnlMtd = totalPnlMtd
  readonly totalPnlYtd = totalPnlYtd
  readonly totalDV01 = totalDV01
  readonly totalCS01 = totalCS01
  readonly totalMktVal = totalMktVal
  readonly sortedPositions = [...BASE_POSITIONS].sort((a, b) => b.pnlToday - a.pnlToday)

  assetFilter: AssetFilter = 'All'
  rowData: Position[] = BASE_POSITIONS
  selected: Position | null = null
  detailRows: [string, string][] = []
  dv01ChartData: any = {}
  dv01ChartOpts: any = {}
  pinnedRow: any[] = [{
    security: 'TOTAL', dv01: totalDV01, cs01: totalCS01,
    pnlToday: totalPnlToday, pnlMtd: totalPnlMtd, pnlYtd: totalPnlYtd,
  }]

  colDefs: ColDef<Position>[] = [
    { field: 'security', headerName: 'Security', width: 160, pinned: 'left', filter: 'agTextColumnFilter',
      cellRenderer: (p: any) => `<div style="display:flex;flex-direction:column;justify-content:center;height:100%;gap:2px"><div style="font-weight:600;font-size:11px">${p.data?.security}</div><div style="font-size:10px;color:var(--ds-muted-foreground);font-family:monospace">${p.data?.cusip}</div></div>` },
    { field: 'assetClass', headerName: 'Class', width: 82, filter: 'agSetColumnFilter',
      cellStyle: (p: any) => ({ color: { Treasury: 'var(--ds-primary)', Corporate: 'var(--ds-buy)', Future: 'var(--ds-warning)', CDS: 'var(--ds-sell)' }[p.value as string] ?? 'var(--ds-muted-foreground)', fontSize: '10px', fontWeight: 500 }) },
    { field: 'direction', headerName: 'Side', width: 78, filter: 'agSetColumnFilter',
      cellRenderer: (p: any) => `<span style="font-size:10px;padding:2px 8px;border-radius:9999px;font-weight:600;background:${p.value === 'Long' ? 'rgba(0,163,108,0.15)' : 'rgba(207,32,47,0.15)'};color:${p.value === 'Long' ? 'var(--ds-buy)' : 'var(--ds-sell)'}">${p.value === 'Long' ? 'LONG' : 'SHORT'}</span>` },
    { field: 'faceValueMM', headerName: 'Size', width: 78, type: 'numericColumn', cellClass: 'font-mono font-semibold', valueFormatter: (p: any) => p.data?.assetClass === 'Future' ? `${p.value} cts` : `$${p.value}MM` },
    { field: 'avgPrice',    headerName: 'Avg Px',   width: 72, type: 'numericColumn', cellClass: 'font-mono', cellStyle: () => ({ color: 'var(--ds-muted-foreground)' }), valueFormatter: (p: any) => fmtPrice(p.value) },
    { field: 'currentPrice',headerName: 'Curr Px',  width: 72, type: 'numericColumn', cellClass: 'font-mono', valueFormatter: (p: any) => fmtPrice(p.value) },
    { field: 'currentYield',headerName: 'Curr Yld', width: 76, type: 'numericColumn', cellClass: 'font-mono', cellStyle: () => ({ color: 'var(--ds-muted-foreground)' }), valueFormatter: (p: any) => p.value > 0 ? fmtYield(p.value) : '—' },
    { field: 'dv01', headerName: 'DV01', width: 76, type: 'numericColumn', cellClass: 'font-mono', cellStyle: (p: any): any => ({ color: p.value >= 0 ? undefined : 'var(--ds-sell)' }), valueFormatter: (p: any) => fmtDV01(p.value) },
    { field: 'cs01', headerName: 'CS01', width: 72, type: 'numericColumn', cellClass: 'font-mono', cellStyle: () => ({ color: 'var(--ds-muted-foreground)' }), valueFormatter: (p: any) => p.value > 0 ? fmtDV01(p.value) : '—' },
    { field: 'pnlToday', headerName: 'P&L Today', width: 90, type: 'numericColumn', filter: 'agNumberColumnFilter',
      cellStyle: (p: any) => ({ color: p.value >= 0 ? 'var(--ds-buy)' : 'var(--ds-sell)', fontFamily: 'monospace', fontWeight: 600 }), valueFormatter: (p: any) => fmtPnL(p.value) },
    { field: 'pnlMtd', headerName: 'P&L MTD', width: 88, type: 'numericColumn', filter: 'agNumberColumnFilter',
      cellStyle: (p: any) => ({ color: p.value >= 0 ? 'var(--ds-buy)' : 'var(--ds-sell)', fontFamily: 'monospace' }), valueFormatter: (p: any) => fmtPnL(p.value) },
    { field: 'pnlYtd', headerName: 'P&L YTD', width: 88, type: 'numericColumn', filter: 'agNumberColumnFilter',
      cellStyle: (p: any) => ({ color: p.value >= 0 ? 'var(--ds-buy)' : 'var(--ds-sell)', fontFamily: 'monospace' }), valueFormatter: (p: any) => fmtPnL(p.value) },
  ]

  defaultColDef: ColDef = { sortable: true, resizable: true, minWidth: 50 }

  constructor(private cdr: ChangeDetectorRef) {}

  ngOnInit(): void {
    this.buildDv01Chart()
    this.buildDv01ChartOpts()
  }

  setFilter(f: AssetFilter): void {
    this.assetFilter = f
    this.rowData = f === 'All' ? BASE_POSITIONS : BASE_POSITIONS.filter(p => p.assetClass === f)
    this.cdr.markForCheck()
  }

  onRowClicked(e: RowClickedEvent<Position>): void {
    this.selected = this.selected?.id === e.data?.id ? null : (e.data ?? null)
    if (this.selected) this.buildDetailRows(this.selected)
    this.cdr.markForCheck()
  }

  onGridReady(e: GridReadyEvent): void { e.api.sizeColumnsToFit() }

  private buildDetailRows(p: Position): void {
    this.detailRows = [
      ['Side',    p.direction],
      ['Class',   p.assetClass],
      ['Size',    p.assetClass === 'Future' ? `${p.faceValueMM} cts` : `$${p.faceValueMM}MM`],
      ['Avg Px',  fmtPrice(p.avgPrice)],
      ['Curr Px', fmtPrice(p.currentPrice)],
      ['Yield',   p.currentYield > 0 ? fmtYield(p.currentYield) : '—'],
      ['DV01',    fmtDV01(p.dv01)],
      ['CS01',    p.cs01 > 0 ? fmtDV01(p.cs01) : '—'],
      ['MTD',     fmtPnL(p.pnlMtd)],
      ['YTD',     fmtPnL(p.pnlYtd)],
    ]
  }

  private buildDv01Chart(): void {
    this.dv01ChartData = {
      labels: DV01_BY_CLASS.map(d => d.label),
      datasets: [{
        label: 'DV01',
        data: DV01_BY_CLASS.map(d => d.dv01),
        backgroundColor: DV01_BY_CLASS.map(d => d.dv01 >= 0 ? 'rgba(0,163,108,0.7)' : 'rgba(207,32,47,0.7)'),
        borderRadius: 3,
        indexAxis: 'y' as any,
      }],
    }
  }

  private buildDv01ChartOpts(): void {
    this.dv01ChartOpts = {
      indexAxis: 'y',
      responsive: true, maintainAspectRatio: false, animation: false,
      plugins: { legend: { display: false }, tooltip: { callbacks: { label: (ctx: any) => '$' + Math.abs(ctx.parsed.x).toLocaleString() + ' DV01' } } },
      scales: {
        x: { ticks: { font: { size: 9 }, color: 'var(--ds-muted-foreground)', callback: (v: number) => '$' + (v / 1000).toFixed(0) + 'K' }, grid: { color: 'rgba(0,0,0,0.05)' } },
        y: { ticks: { font: { size: 10 }, color: 'var(--ds-muted-foreground)' }, grid: { display: false } },
      },
    }
  }

  barPct(pnl: number): number { return Math.min(Math.abs(pnl) / 45000 * 100, 100) }
}
