// react-app/src/components/layout/Header.tsx
import { cn } from '@/lib/utils'
import { useTheme } from '@/components/theme/ThemeProvider'
import { Sun, Moon, Search, Palette } from 'lucide-react'
import type { AppTab } from './AppShell'

function MarketsUIIcon() {
  return (
    <svg width="20" height="20" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
      <rect width="32" height="32" rx="8" fill="#1652f0"/>
      <polyline
        points="4,22 9,16 13,18.5 19,8 25,12"
        stroke="white"
        strokeWidth="2.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <circle cx="25" cy="12" r="3" fill="white"/>
    </svg>
  )
}

const TABS: AppTab[] = ['Dashboard', 'Components']

interface HeaderProps {
  activeTab: AppTab
  onTabChange: (tab: AppTab) => void
}

export function Header({ activeTab, onTabChange }: HeaderProps) {
  const { theme, toggleTheme } = useTheme()

  return (
    <header className="flex items-center justify-between border-b border-border bg-card px-4 h-11 shrink-0">
      <div className="flex items-center gap-4">
        <div className="flex items-center gap-1.5 font-semibold text-foreground">
          <MarketsUIIcon />
          <span className="text-sm tracking-tight">MarketsUI</span>
        </div>
        <nav className="flex items-center">
          {TABS.map(tab => (
            <button
              key={tab}
              onClick={() => onTabChange(tab)}
              className={cn(
                'flex items-center gap-1.5 px-3 py-2 text-xs font-medium transition-colors border-b-2 -mb-px',
                activeTab === tab
                  ? 'text-foreground border-primary'
                  : 'border-transparent text-muted-foreground hover:text-foreground'
              )}
            >
              {tab === 'Components' && <Palette className="w-3 h-3" />}
              {tab}
            </button>
          ))}
        </nav>
      </div>
      <div className="flex items-center gap-2">
        <button className="flex items-center gap-2 px-3 py-1.5 text-xs text-muted-foreground bg-secondary border border-border rounded-full hover:text-foreground hover:border-border/80 transition-colors">
          <Search className="w-3 h-3" />
          <span>Search...</span>
          <kbd className="text-[10px] bg-accent px-1.5 rounded font-sans">⌘K</kbd>
        </button>
        <button
          onClick={toggleTheme}
          className="p-1.5 rounded-md text-muted-foreground hover:text-foreground hover:bg-secondary transition-colors"
          title={`Switch to ${theme === 'dark' ? 'light' : 'dark'} mode`}
        >
          {theme === 'dark' ? <Sun className="w-4 h-4" /> : <Moon className="w-4 h-4" />}
        </button>
      </div>
    </header>
  )
}

// angular-app/src/app/layout/header.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core'
import { CommonModule } from '@angular/common'
import { ThemeService } from '../theme/theme.service'
import { Button } from 'primeng/button'

export type AppTab = 'Dashboard' | 'Components'

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [CommonModule, Button],
  template: `
    <header class="ds-header">
      <div class="ds-header-left">
        <div class="ds-logo">
          <!-- MarketsUI icon: blue rounded square with line chart -->
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <rect width="24" height="24" rx="6" fill="#1652f0"/>
            <polyline points="4,16 8,11 12,13 16,7 20,9" stroke="white" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" fill="none"/>
          </svg>
          <span>MarketsUI</span>
        </div>
        <nav class="ds-nav">
          @for (tab of tabLabels; track tab) {
            <button
              class="ds-nav-tab"
              [class.ds-nav-active]="activeTab === tab"
              (click)="tabChange.emit(tab)"
            >
              @if (tab === 'Components') {
                <i class="pi pi-palette" style="font-size:0.65rem;margin-right:3px"></i>
              }
              {{ tab }}
            </button>
          }
        </nav>
      </div>
      <div class="ds-header-right">
        <div class="ds-search-trigger">
          <i class="pi pi-search"></i>
          <span>Search...</span>
          <kbd>⌘K</kbd>
        </div>
        <p-button
          [icon]="themeService.isDark() ? 'pi pi-sun' : 'pi pi-moon'"
          [text]="true"
          [rounded]="true"
          size="small"
          (onClick)="themeService.toggleTheme()"
        />
      </div>
    </header>
  `,
  styles: [`
    .ds-header {
      display: flex; align-items: center; justify-content: space-between;
      border-bottom: 1px solid var(--ds-border);
      background: var(--ds-card);
      padding: 0 1rem; height: 2.75rem; flex-shrink: 0;
    }
    .ds-header-left { display: flex; align-items: center; gap: 1rem; }
    .ds-logo {
      display: flex; align-items: center; gap: 0.5rem;
      font-weight: 700; font-size: 0.875rem; color: var(--ds-foreground);
      letter-spacing: -0.02em;
    }
    .ds-nav { display: flex; align-items: center; }
    .ds-nav-tab {
      padding: 0.5rem 0.75rem; font-size: 0.75rem; font-weight: 500;
      background: none; border: none; border-bottom: 2px solid transparent;
      color: var(--ds-muted-foreground); cursor: pointer;
      transition: color 0.15s, border-color 0.15s;
      display: flex; align-items: center; gap: 0.25rem;
      height: 2.75rem;
    }
    .ds-nav-tab:hover { color: var(--ds-foreground); }
    .ds-nav-active { color: var(--ds-foreground); border-bottom-color: var(--ds-primary); }
    .ds-header-right { display: flex; align-items: center; gap: 0.5rem; }
    .ds-search-trigger {
      display: flex; align-items: center; gap: 0.5rem;
      padding: 0.25rem 0.75rem; border-radius: 4px;
      background: var(--ds-secondary); color: var(--ds-muted-foreground);
      font-size: 0.75rem; cursor: pointer;
    }
    .ds-search-trigger:hover { color: var(--ds-foreground); }
    .ds-search-trigger kbd {
      font-size: 0.625rem; background: var(--ds-accent);
      padding: 0 0.25rem; border-radius: 2px;
    }
  `],
})
export class HeaderComponent {
  @Input() activeTab: AppTab = 'Dashboard'
  @Output() tabChange = new EventEmitter<AppTab>()
  tabLabels: AppTab[] = ['Dashboard', 'Components']
  constructor(public themeService: ThemeService) {}
}
