// angular-app/src/app/trading/order-entry.component.ts
import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Button } from 'primeng/button';
import { Select } from 'primeng/select';
import { InputNumber } from 'primeng/inputnumber';
import { Dialog } from 'primeng/dialog';

@Component({
  selector: 'app-order-entry',
  standalone: true,
  imports: [CommonModule, FormsModule, Button, Select, InputNumber, Dialog],
  template: `
    <div class="ds-panel ds-order-entry">
      <div class="ds-order-symbol">
        <span class="ds-bold">AAPL</span>
        <span class="ds-mono ds-muted">\$263.90</span>
      </div>

      <!-- Buy/Sell Toggle -->
      <div class="ds-toggle-group">
        <button
          class="ds-toggle-btn"
          [class.ds-toggle-buy]="side() === 'buy'"
          [class.ds-toggle-inactive]="side() !== 'buy'"
          (click)="side.set('buy')"
        >Buy</button>
        <button
          class="ds-toggle-btn"
          [class.ds-toggle-sell]="side() === 'sell'"
          [class.ds-toggle-inactive]="side() !== 'sell'"
          (click)="side.set('sell')"
        >Sell</button>
      </div>

      <!-- Order Type -->
      <div class="ds-field">
        <label class="ds-field-label">Order type</label>
        <p-select
          [options]="orderTypes"
          [(ngModel)]="orderType"
          [style]="{ width: '100%' }"
          size="small"
        />
      </div>

      <!-- Quantity -->
      <div class="ds-field">
        <label class="ds-field-label">Quantity</label>
        <p-inputNumber
          [(ngModel)]="quantity"
          [showButtons]="true"
          buttonLayout="horizontal"
          [min]="1"
          incrementButtonIcon="pi pi-plus"
          decrementButtonIcon="pi pi-minus"
          [style]="{ width: '100%' }"
          [inputStyle]="{ textAlign: 'center', fontFamily: 'var(--ds-font-mono)', fontSize: '0.75rem' }"
          size="small"
        />
      </div>

      <!-- Limit Price -->
      @if (orderType !== 'Market') {
        <div class="ds-field">
          <label class="ds-field-label">{{ orderType === 'Limit' ? 'Limit price' : 'Stop price' }}</label>
          <p-inputNumber
            [(ngModel)]="limitPrice"
            mode="currency"
            currency="USD"
            [minFractionDigits]="2"
            [maxFractionDigits]="2"
            [showButtons]="true"
            buttonLayout="horizontal"
            [step]="0.01"
            incrementButtonIcon="pi pi-plus"
            decrementButtonIcon="pi pi-minus"
            [style]="{ width: '100%' }"
            [inputStyle]="{ fontFamily: 'var(--ds-font-mono)', fontSize: '0.75rem' }"
            size="small"
          />
          <div class="ds-hint">Bid $263.82 · Ask $263.93</div>
        </div>
      }

      <!-- Time in Force -->
      <div class="ds-field">
        <label class="ds-field-label">Time in force</label>
        <p-select
          [options]="timeOptions"
          [(ngModel)]="timeInForce"
          [style]="{ width: '100%' }"
          size="small"
        />
      </div>

      <!-- Estimated Cost -->
      <div class="ds-cost-section">
        <div class="ds-cost-row">
          <span class="ds-sell-text ds-bold">Estimated cost</span>
          <span class="ds-mono ds-bold">{{ '$' + estimatedCost() }}</span>
        </div>
        <div class="ds-hint">Buying power $0.00</div>
      </div>

      <!-- Submit -->
      <p-button
        [label]="(side() === 'buy' ? 'Buy' : 'Sell') + ' AAPL'"
        [style]="{
          width: '100%',
          backgroundColor: side() === 'buy' ? 'var(--ds-buy)' : 'var(--ds-sell)',
          borderColor: side() === 'buy' ? 'var(--ds-buy)' : 'var(--ds-sell)',
          fontSize: '0.75rem'
        }"
        (onClick)="showConfirm.set(true)"
        size="small"
      />
    </div>

    <!-- Confirmation Dialog -->
    <p-dialog
      header="Confirm Order"
      [(visible)]="confirmVisible"
      [modal]="true"
      [style]="{ width: '20rem' }"
      [closable]="true"
    >
      <div class="ds-confirm-body">
        <div class="ds-confirm-row">
          <span class="ds-muted">Symbol</span>
          <span class="ds-bold">AAPL</span>
        </div>
        <div class="ds-confirm-row">
          <span class="ds-muted">Side</span>
          <span [class]="side() === 'buy' ? 'ds-buy-text ds-bold' : 'ds-sell-text ds-bold'">
            {{ side().toUpperCase() }}
          </span>
        </div>
        <div class="ds-confirm-row">
          <span class="ds-muted">Type</span>
          <span class="ds-bold">{{ orderType }}</span>
        </div>
        <div class="ds-confirm-row">
          <span class="ds-muted">Quantity</span>
          <span class="ds-mono">{{ quantity }}</span>
        </div>
        @if (orderType !== 'Market') {
          <div class="ds-confirm-row">
            <span class="ds-muted">Price</span>
            <span class="ds-mono">{{ '$' + limitPrice.toFixed(2) }}</span>
          </div>
        }
      </div>
      <ng-template #footer>
        <div class="ds-confirm-actions">
          <p-button label="Cancel" [text]="true" size="small" (onClick)="showConfirm.set(false)" />
          <p-button
            [label]="(side() === 'buy' ? 'Buy' : 'Sell') + ' AAPL'"
            [style]="{
              backgroundColor: side() === 'buy' ? 'var(--ds-buy)' : 'var(--ds-sell)',
              borderColor: side() === 'buy' ? 'var(--ds-buy)' : 'var(--ds-sell)'
            }"
            size="small"
            (onClick)="showConfirm.set(false)"
          />
        </div>
      </ng-template>
    </p-dialog>
  `,
  styles: [`
    :host { display: block; height: 100%; width: 100%; overflow: auto; }
    .ds-order-entry { padding: 0.75rem; display: flex; flex-direction: column; gap: 0.75rem; }
    .ds-order-symbol { display: flex; align-items: center; gap: 0.5rem; font-size: 0.75rem; }
    .ds-toggle-group {
      display: flex;
      border: 1px solid var(--ds-border);
      border-radius: 4px;
      overflow: hidden;
    }
    .ds-toggle-btn {
      flex: 1;
      padding: 0.375rem;
      font-size: 0.75rem;
      font-weight: 500;
      border: none;
      cursor: pointer;
      transition: all 0.15s;
    }
    .ds-toggle-buy { background: var(--ds-buy); color: #1a1a22; }
    .ds-toggle-sell { background: var(--ds-sell); color: #fff; }
    .ds-toggle-inactive {
      background: var(--ds-secondary);
      color: var(--ds-muted-foreground);
    }
    .ds-toggle-inactive:hover { color: var(--ds-foreground); }
    .ds-field { display: flex; flex-direction: column; gap: 0.25rem; }
    .ds-field-label { font-size: 0.6875rem; color: var(--ds-muted-foreground); }
    .ds-cost-section {
      border-top: 1px solid var(--ds-border);
      padding-top: 0.5rem;
    }
    .ds-cost-row {
      display: flex;
      justify-content: space-between;
      font-size: 0.75rem;
    }
    .ds-mono { font-family: var(--ds-font-mono); }
    .ds-bold { font-weight: 500; }
    .ds-muted { color: var(--ds-muted-foreground); font-size: 0.75rem; }
    .ds-hint { font-size: 0.625rem; color: var(--ds-muted-foreground); margin-top: 0.125rem; }
    .ds-buy-text { color: var(--ds-buy); }
    .ds-sell-text { color: var(--ds-sell); }
    .ds-confirm-body { display: flex; flex-direction: column; gap: 0.5rem; }
    .ds-confirm-row {
      display: flex;
      justify-content: space-between;
      font-size: 0.75rem;
    }
    .ds-confirm-actions { display: flex; gap: 0.5rem; justify-content: flex-end; }
    .ds-panel {
      background: var(--ds-card);
      border: 1px solid var(--ds-border);
      border-radius: 4px;
    }
  `],
})
export class OrderEntryComponent {
  side = signal<'buy' | 'sell'>('buy');
  orderType = 'Limit';
  orderTypes = ['Market', 'Limit', 'Stop'];
  quantity = 1;
  limitPrice = 263.93;
  timeInForce = 'Good for day';
  timeOptions = ['Good for day', 'Good til canceled'];
  showConfirm = signal(false);

  get confirmVisible() { return this.showConfirm(); }
  set confirmVisible(v: boolean) { this.showConfirm.set(v); }

  estimatedCost(): string {
    return (this.quantity * this.limitPrice).toFixed(2);
  }
}

// react-app/src/components/trading/OrderEntry.tsx
import { useState } from 'react'
import { cn } from '@/lib/utils'

type Side = 'buy' | 'sell'
type OrderType = 'market' | 'limit' | 'stop'

export function OrderEntry() {
  const [side, setSide] = useState<Side>('buy')
  const [orderType, setOrderType] = useState<OrderType>('limit')
  const [quantity, setQuantity] = useState(1)
  const [limitPrice, setLimitPrice] = useState('263.93')
  const [showConfirm, setShowConfirm] = useState(false)

  const isBuy = side === 'buy'

  return (
    <>
      <div className="bg-card h-full overflow-auto p-3 flex flex-col gap-3">
        <div className="flex items-center gap-2">
          <span className="text-xs font-medium">AAPL</span>
          <span className="text-xs font-mono text-muted-foreground">$263.90</span>
        </div>

        {/* Buy/Sell Toggle */}
        <div className="flex rounded-md overflow-hidden border border-border">
          <button
            onClick={() => setSide('buy')}
            className={cn(
              'flex-1 py-1.5 text-xs font-medium transition-colors',
              isBuy ? 'bg-buy text-buy-foreground' : 'bg-secondary text-muted-foreground hover:text-foreground'
            )}
          >
            Buy
          </button>
          <button
            onClick={() => setSide('sell')}
            className={cn(
              'flex-1 py-1.5 text-xs font-medium transition-colors',
              !isBuy ? 'bg-sell text-sell-foreground' : 'bg-secondary text-muted-foreground hover:text-foreground'
            )}
          >
            Sell
          </button>
        </div>

        {/* Order Type */}
        <div>
          <label className="text-[11px] text-muted-foreground mb-1 block">Order type</label>
          <select
            value={orderType}
            onChange={e => setOrderType(e.target.value as OrderType)}
            className="w-full bg-secondary border border-border rounded-md px-2 py-1.5 text-xs focus:outline-none focus:ring-1 focus:ring-ring"
          >
            <option value="market">Market</option>
            <option value="limit">Limit</option>
            <option value="stop">Stop</option>
          </select>
        </div>

        {/* Quantity */}
        <div>
          <label className="text-[11px] text-muted-foreground mb-1 block">Quantity</label>
          <div className="flex items-center border border-border rounded-md overflow-hidden">
            <button
              onClick={() => setQuantity(Math.max(1, quantity - 1))}
              className="px-2 py-1.5 bg-secondary text-muted-foreground hover:text-foreground transition-colors text-xs"
            >
              −
            </button>
            <input
              type="number"
              value={quantity}
              onChange={e => setQuantity(Math.max(1, parseInt(e.target.value) || 1))}
              className="flex-1 bg-transparent text-center text-xs font-mono py-1.5 focus:outline-none [appearance:textfield] [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none"
            />
            <button
              onClick={() => setQuantity(quantity + 1)}
              className="px-2 py-1.5 bg-secondary text-muted-foreground hover:text-foreground transition-colors text-xs"
            >
              +
            </button>
          </div>
        </div>

        {/* Limit Price (shown for limit and stop orders) */}
        {orderType !== 'market' && (
          <div>
            <label className="text-[11px] text-muted-foreground mb-1 block">
              {orderType === 'limit' ? 'Limit price' : 'Stop price'}
            </label>
            <div className="flex items-center border border-border rounded-md overflow-hidden">
              <span className="px-2 text-xs text-muted-foreground">$</span>
              <input
                type="text"
                value={limitPrice}
                onChange={e => setLimitPrice(e.target.value)}
                className="flex-1 bg-transparent text-xs font-mono py-1.5 focus:outline-none"
              />
              <div className="flex flex-col border-l border-border">
                <button
                  onClick={() => setLimitPrice((parseFloat(limitPrice) + 0.01).toFixed(2))}
                  className="px-1.5 py-0.5 text-[10px] text-muted-foreground hover:text-foreground hover:bg-secondary transition-colors"
                >
                  +
                </button>
                <button
                  onClick={() => setLimitPrice((parseFloat(limitPrice) - 0.01).toFixed(2))}
                  className="px-1.5 py-0.5 text-[10px] text-muted-foreground hover:text-foreground hover:bg-secondary transition-colors border-t border-border"
                >
                  −
                </button>
              </div>
            </div>
            <div className="text-[10px] text-muted-foreground mt-1">
              Bid $263.82 &middot; Ask $263.93
            </div>
          </div>
        )}

        {/* Time in Force */}
        <div>
          <label className="text-[11px] text-muted-foreground mb-1 block">Time in force</label>
          <select className="w-full bg-secondary border border-border rounded-md px-2 py-1.5 text-xs focus:outline-none focus:ring-1 focus:ring-ring">
            <option>Good for day</option>
            <option>Good til canceled</option>
          </select>
        </div>

        {/* Estimated Cost */}
        <div className="border-t border-border pt-2">
          <div className="flex justify-between text-xs">
            <span className="text-sell font-medium">Estimated cost</span>
            <span className="font-mono font-medium">
              ${(quantity * parseFloat(limitPrice || '0')).toFixed(2)}
            </span>
          </div>
          <div className="text-[10px] text-muted-foreground">Buying power $0.00</div>
        </div>

        {/* Submit */}
        <button
          onClick={() => setShowConfirm(true)}
          className={cn(
            'w-full py-2 rounded-md text-xs font-medium transition-colors',
            isBuy
              ? 'bg-buy text-buy-foreground hover:bg-buy/90'
              : 'bg-sell text-sell-foreground hover:bg-sell/90'
          )}
        >
          {isBuy ? 'Buy' : 'Sell'} AAPL
        </button>
      </div>

      {/* Confirmation Dialog */}
      {showConfirm && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60">
          <div className="bg-card border border-border rounded-lg p-4 w-80 shadow-lg">
            <h3 className="text-sm font-semibold mb-3">Confirm Order</h3>
            <div className="space-y-2 text-xs">
              <div className="flex justify-between">
                <span className="text-muted-foreground">Symbol</span>
                <span className="font-medium">AAPL</span>
              </div>
              <div className="flex justify-between">
                <span className="text-muted-foreground">Side</span>
                <span className={cn('font-medium', isBuy ? 'text-buy' : 'text-sell')}>
                  {side.toUpperCase()}
                </span>
              </div>
              <div className="flex justify-between">
                <span className="text-muted-foreground">Type</span>
                <span className="font-medium capitalize">{orderType}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-muted-foreground">Quantity</span>
                <span className="font-mono">{quantity}</span>
              </div>
              {orderType !== 'market' && (
                <div className="flex justify-between">
                  <span className="text-muted-foreground">Price</span>
                  <span className="font-mono">${limitPrice}</span>
                </div>
              )}
            </div>
            <div className="flex gap-2 mt-4">
              <button
                onClick={() => setShowConfirm(false)}
                className="flex-1 py-1.5 text-xs rounded-md border border-border bg-secondary hover:bg-accent transition-colors"
              >
                Cancel
              </button>
              <button
                onClick={() => setShowConfirm(false)}
                className={cn(
                  'flex-1 py-1.5 text-xs rounded-md font-medium transition-colors',
                  isBuy
                    ? 'bg-buy text-buy-foreground hover:bg-buy/90'
                    : 'bg-sell text-sell-foreground hover:bg-sell/90'
                )}
              >
                {isBuy ? 'Buy' : 'Sell'} AAPL
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  )
}
